In [3]:
import pandas as pd

In [5]:
customers_df = pd.read_csv('../data/customers.csv')
products_df = pd.read_csv('../data/products.csv')

In [8]:
sel = customers_df.loc[
    customers_df['customer_id'].between(5000, 5010),
    ['customer_id', 'name', 'city']
]

sel.sort_values('customer_id', ascending=True)

      customer_id name city
4994         5000  조지태   서울
4480         5001  안영진   세종
2520         5002  김하재  서울
2955         5003  장성태   고양
4945         5004  안아하   세종
3482         5005  홍우지   부산
4302         5006  강수아   고양
3186         5007  신선수   서울
3249         5008  최예예   수원
1412         5009  박태재   대전
4981         5010  윤예민   서울

In [10]:
#서울, 부산에 있는 고객 추출
customers_df['city'].isin(['서울', '부산'])
customers_df.loc[
    customers_df['city'].isin(['서울','부산']),
    ['name', 'city']
                 ]

     name city
1     박준선   서울
3     한재하   서울
8     권재현   서울
10    윤수현   서울
16    박재태   서울
...   ...  ...
4986  신예경   부산
4988  전민예   서울
4991  정성하   서울
4994  조지태   서울
4995  정우은   서울

[1447 rows x 2 columns]

In [ ]:
#서울, 부산에 있는 고객 외 추출
customers_df['city'].isin(['서울', '부산'])
customers_df.loc[
    ~customers_df['city'].isin(['서울','부산']),
    ['name', 'city']
]

     name city
0     권준서   부산
2     전영경   인천
4     송준연   대전
5     최현우   고양
6     전선태   광주
...   ...  ...
4993  최하수   대구
4996  이예재   고양
4997  조아준   인천
4998  장성우  대전
4999  이하민   수원

[3553 rows x 2 columns]

In [12]:
# 상품명 :  홍차가 포함된 상품명
products_df['product_name']

0           플러스 홍차
1         프리미엄 노트북
2        프리미엄 원두커피
3          베이직 마우스
4           베이직 홍차
          ...
495         베이직 선반
496         데일리 시집
497    프리미엄 스킨케어세트
498          코어 샴푸
499     베이직 스킨케어세트
Name: product_name, Length: 500, dtype: str