In [4]:
#데이터 프레임을 딕셔너리로 직접 생성
import pandas as pd

sample = {
    "product_name":['코어 티셔츠', '베이지 노트북', '데일리 원두커피'],
    "category":['의류', '전자', '식품'],
    "price":[39000, 89000, 15000]
}

# print(type(sample))
sample_df = pd.DataFrame(sample)   #sample Dataframe 생성
sample_df.head()

  product_name category  price
0       코어 티셔츠       의류  39000
1      베이지 노트북       전자  89000
2     데일리 원두커피       식품  15000

In [6]:
#인덱스 추출
#sample_df.index : ndarray(다차원배열, numpy에서 제공하는 자료구조)
# 이걸 list로 변환하면

print(f"Index : {sample_df.index.tolist()}")

Index : [0, 1, 2]

In [ ]:
# columnn 정보 추출
# column 명만 추출하려면
# sample
# 리스트를 뽑았다 -> 반복 가능하다

sample_df.columns.tolist()

['product_name', 'category', 'price']

In [ ]:
#data frame 의 data type 추출  -> series를 return한다       

sample_df.dtypes

product_name      str
category          str
price           int64
dtype: object

In [14]:
#고객 데이터에서 city column 꺼내서 정보 확인
customers_df=pd.read_csv("../data/customers.csv")
customers_df.head(20)

    customer_id name gender  birth_date signup_date city                 email
0          3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1          1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2          4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3          4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4          3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com
5          1992  최현우      여  1999-08-31  2021-06-22   고양  user1992@example.com
6          3499  전선태      남  2005-03-12  2021-07-02   광주                   NaN
7          2183  장예성      M  1992-03-22  2021-02-19   수원  user2183@example.com
8          5090  권재현      M  1972-08-26  2020-10-02   서울                   NaN
9          2209  홍준영      M  1976-06-16  2024-03-10   수원  user2209@example.com
10         5055  윤수현      F  1972-03-11  2021-05-20   서울  user5055@example.com
11         5882  임하우      여  1995-11-08  2020-04-29   수원  user5882@example.com
12         3558  김수도      여  1954-05-15  2023-07-10   광주  user3558@example.com
13         4018  오민서      F  1964-04-27  2023-02-20   울산  user4018@example.com
14         5539  송서현      M  1984-08-31  2022-10-17   대구  user5539@example.com
15         5434  오예영      여  1978-05-20  2022-05-14   서울  user5434@example.com
16         3699  박재태      M  1976-01-27  2020-06-08   서울  user3699@example.com
17         1307  오준수      남  1986-10-25  2023-01-07   서울  user1307@example.com
18         1480  강태재      M  2002-09-14  2022-12-14   부산  user1480@example.com
19         3333  안민하      M  1968-07-21  2020-03-06   서울  user3333@example.com

In [ ]:
#city column
# city = customers_df['컬럼명']
city = customers_df['city']
city.head(3) #series 에 있는 head라는 method를 호출해서 3개만 확인

0     부산
1     서울
2     인천
Name: city, dtype: str

In [16]:
#name 접근
# type(city)   pandas(모듈).Series(클래스)
type(city).__name__

'Series'

In [ ]:
#데이터 타입 확인
city.dtype

: