In [ ]:
#데이터 훑어보기: head(), info(), describe(), value_counts()
#value 
import pandas as pd

orders = pd.read_csv(
    '../data/orders.csv',
    parse_dates=['order_datetime']
)

# orders.head(3)
# orders.tail(3)

        order_id  customer_id      order_datetime channel     status
199997     88502         3265 2024-01-20 06:44:00     app  delivered
199998     62264         2403 2024-03-21 00:22:40     web  delivered
199999      1963         3439 2024-01-01 00:58:02     app   canceled

In [ ]:
#데이터프레임의 정보추출
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [9]:
#2. describe(): 기본 통계랑(합, 평균, 최대, 최소, 표준편차(분산), 사분위) 구한다
order_items_df = pd.read_csv('../data/order_items.csv')
order_items_df.head(3)

   order_item_id  order_id  product_id  quantity  unit_price  discount
0          59256    114625           3         1     20300.0      0.05
1         230587     66337          80         2     90000.0      0.45
2         279813    163343           3         3     20300.0      0.23

In [13]:
# order_items_df.info()

#단일 컬럼 추출 vs 다중 컬럼 추출

# 다중 컬럼
order_items_df[['quantity', 'unit_price', 'discount' ]] #dataframe return
order_items_df[['quantity', 'unit_price', 'discount' ]].head(3)

   quantity  unit_price  discount
0         1     20300.0      0.05
1         2     90000.0      0.45
2         3     20300.0      0.23

In [ ]:
#dataframe이니까 describe 로 통계랑도 가능
order_items_df[['quantity', 'unit_price', 'discount']].describe()

            quantity     unit_price       discount
count  500000.000000  484887.000000  500000.000000
mean        2.997008   50925.557707       0.249688
std         1.418193   48908.412198       0.144496
min        -2.000000    1000.000000       0.000000
25%         2.000000   15100.000000       0.120000
50%         3.000000   27000.000000       0.250000
75%         4.000000   73700.000000       0.370000
max         5.000000  291000.000000       0.500000

In [15]:
#value_counts() :값의 개수 확인
#상품에서 카테고리별 개수
products_df = pd.read_csv('../data/products.csv')
products_df.head(3)

   product_id product_name category    price     cost
0         119       플러스 홍차       식품        0   3700.0
1          95     프리미엄 노트북       전자  68600.0  28900.0
2         112    프리미엄 원두커피       식품  10500.0   4700.0

In [18]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    int64
 1   product_name  500 non-null    str
 2   category      500 non-null    str
 3   price         500 non-null    str
 4   cost          500 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 35.5 KB

In [19]:

products_df['category'].value_counts()

category
도서     90
전자     79
식품     75
가구     71
의류     70
뷰티     68
전자     13
가구      9
의류      9
도서      7
뷰티      5
식품      4
Name: count, dtype: int64

In [21]:
#['식품', '전자', '식품 ', '의류', '뷰티', '가구', '가구 ', '뷰티 ', '전자 ', '도서', '의류 ', '도서 ']
products_df['category'].unique()


#
print(products_df['category'].nunique())

12

In [22]:
#missing data handling
# 결측 개수 
# 고객데이터
customers_df = pd.read_csv('../data/customers.csv')
customers_df.head()

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [23]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5000 non-null   int64
 1   name         5000 non-null   str
 2   gender       4696 non-null   str
 3   birth_date   4616 non-null   str
 4   signup_date  5000 non-null   str
 5   city         5000 non-null   str
 6   email        4752 non-null   str
dtypes: int64(1), str(6)
memory usage: 544.3 KB

In [24]:
# 결측치 - 생일 데이터 없는 고객의 수 확인
customers_df['birth_date'].isna()  #isna() 없니? 없으면 true, 있으면 false

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: birth_date, Length: 5000, dtype: bool

In [ ]:
#단일 컬럼의 결측 개수
customers_df['birth_date'].isna().sum()   #없는 거 (true)의 개수

np.int64(384)

In [ ]:
#다중 컬럼의 결측 개수 세기
customers_df.isna().sum()

customer_id      0
name             0
gender         304
birth_date     384
signup_date      0
city             0
email          248
dtype: int64

:

In [28]:
customers_df.isna().sum()[['gender', 'birth_date']]

gender        304
birth_date    384
dtype: int64